module Constants
  VULGATE_BIBLE_FILE = Rails.root.join('lib', 'vuldat.txt')
  LATIN_TITLES = {
    gen: "Genesis",
    exo: "Exodus",
    lev: "Leviticus",
    num: "Numeri",
    deu: "Deuteronomium",
    jos: "Josue",
    jdg: "Judicum",
    rut: "Ruth",
    sa1: "Regum I",
    sa2: "Regum II",
    kg1: "Regum III",
    Kg2: "Regum IV",
    ch1: "Paralipomenon I",
    ch2: "Paralipomenon II",
    ezr: "Esdrae",
    neh: "Nehemiae",
    tob: "Tobiae",
    jdt: "Judith",
    est: "Esther",
    job: "Job",
    psa: "Psalmi",
    pro: "Proverbia",
    ecc: "Ecclesiastes",
    sol: "Canticum Canticorum",
    wis: "Sapientia",
    sir: "Ecclesiasticus",
    isa: "Isaias",
    jer: "Jeremias",
    lam: "Lamentationes",
    bar: "Baruch",
    eze: "Ezechiel",
    dan: "Daniel",
    hos: "Osee",
    joe: "Joel",
    amo: "Amos",
    oba: "Abdias",
    jon: "Jonas",
    mic: "Michaea",
    nah: "Nahum",
    hab: "Habacuc",
    zep: "Sophonias",
    hag: "Aggaeus",
    zac: "Zacharias",
    mal: "Malachias",
    ma1: "Machabaeorum I",
    ma2: "Machabaeorum II",
    mat: "Secundum Matthaeum",
    mar: "Secundum Marcum",
    luk: "Secundum Lucam",
    joh: "Secundum Ioannem",
    act: "Actus Apostolorum",
    rom: "Ad Romanos",
    co1: "Ad Corinthios I",
    co2: "Ad Corinthios II",
    gal: "Ad Galatas",
    eph: "Ad Ephesios",
    phi: "Ad Philippenses",
    col: "Ad Colossenses",
    th1: "Ad Thessalonicenses I",
    th2: "Ad Thessalonicenses II",
    ti1: "Ad Timotheum I",
    ti2: "Ad Timotheum II",
    tit: "Ad Titum",
    plm: "Ad Philemonem",
    heb: "Ad Hebraeos",
    jam: "Epistula Iacobi",
    pe1: "Epistula Petri I",
    pe2: "Epistula Petri II",
    jo1: "Epistula Ioannis I",
    jo2: "Epistula Ioannis II",
    jo3: "Epistula Ioannis III",
    jde: "Epistula Iudae",
    rev: "Apocalypsis Ioannis"
  }
end
